import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Scale, CheckCircle, AlertTriangle, FileText } from 'lucide-react';
import { Button } from "@/components/ui/button";
import AdBanner from '../components/AdBanner';

const TermsPage = () => {
  const navigate = useNavigate();

  useEffect(() => {
    document.title = "Terms of Service | Inzeedo Invoice Generator";
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 text-slate-800 dark:text-slate-200">
      <div className="max-w-4xl mx-auto px-6 py-8">
        {/* Header */}
        <div className="flex items-center justify-between gap-4 mb-8 pb-6 border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400 flex items-center justify-center">
              <Scale className="h-6 w-6" />
            </div>
            <div>
              <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">Terms of Service</h1>
              <p className="text-xs text-slate-500 dark:text-slate-400">Effective Date: September 14, 2026</p>
            </div>
          </div>
          <Button variant="outline" size="sm" onClick={() => navigate('/')} className="shadow-sm">
            <ArrowLeft className="mr-2 h-4 w-4" /> Home
          </Button>
        </div>

        {/* Terms Content */}
        <div className="bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 md:p-10 shadow-xl shadow-slate-200/50 dark:shadow-slate-950/50 space-y-8 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              1. Acceptance of Terms
            </h2>
            <p className="text-slate-600 dark:text-slate-300">
              By accessing or using the <strong>Inzeedo Invoice Generator</strong> website (`https://invoicer.inzeedo.lk`), you agree to be bound by these Terms of Service provided by <strong>Inzeedo (PVT) Ltd.</strong>. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <FileText className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              2. Free Service & User Responsibilities
            </h2>
            <p className="text-slate-600 dark:text-slate-300">
              Inzeedo provides an online tool for generating PDF invoices, bills, and receipts for personal and commercial use. You are solely responsible for ensuring the accuracy, legality, and compliance of the invoice data you input (including tax rates, customer names, product amounts, and business details).
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              3. Disclaimer of Warranties & Limitation of Liability
            </h2>
            <p className="text-slate-600 dark:text-slate-300">
              The service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind. Inzeedo (PVT) Ltd. shall not be liable for any indirect, incidental, or consequential damages arising from the use or inability to use the invoice generator tool, PDF downloads, or ad interactions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white">4. Intellectual Property</h2>
            <p className="text-slate-600 dark:text-slate-300">
              All branding, logos, software logic, interface designs, and code templates are the exclusive intellectual property of Inzeedo (PVT) Ltd. All invoices generated by users belong to the user.
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-slate-100 dark:border-slate-800">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white">5. Governing Law</h2>
            <p className="text-slate-600 dark:text-slate-300">
              These terms shall be governed by and construed in accordance with the laws of Sri Lanka.
            </p>
          </section>
        </div>

        <AdBanner />

        {/* Footer */}
        <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4">
          <p>© {new Date().getFullYear()} Inzeedo (PVT) Ltd. All rights reserved.</p>
          <div className="flex gap-4">
            <button onClick={() => navigate('/privacy')} className="hover:underline">Privacy Policy</button>
            <button onClick={() => navigate('/terms')} className="hover:underline font-medium text-blue-600 dark:text-blue-400">Terms of Service</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
